from .dfa import DFA
from .nfa import NFA
from .regex import *

VTYPE_dfa=DFA(NFA(VTYPE))

INTEGER_dfa=DFA(NFA(INTEGER))

CHARACTER_dfa=DFA(NFA(CHARACTER))

BOOLEAN_dfa=DFA(NFA(BOOLEAN))

STRING_LITERAL_dfa=DFA(NFA(STRING_LITERAL)) 

ID_dfa=DFA(NFA(ID))

IF_dfa=DFA(NFA(IF))

ELSE_dfa=DFA(NFA(ELSE))

WHILE_dfa=DFA(NFA(WHILE))

CLASS_dfa=DFA(NFA(CLASS))

RETURN_dfa=DFA(NFA(RETURN))

OP_dfa=DFA(NFA(OP))

SEMI_COLON_dfa=DFA(NFA(SEMI_COLON))

LPAREN_dfa=DFA(NFA(LPAREN))

RPAREN_dfa=DFA(NFA(RPAREN))

LBRACE_dfa=DFA(NFA(LBRACE))

RBRACE_dfa=DFA(NFA(RBRACE))

LBRACKET_dfa=DFA(NFA(LBRACKET))

RBRACKET_dfa=DFA(NFA(RBRACKET))

WHITESPACE_dfa=DFA(NFA(WHITESPACE))

ASSIGN_dfa=DFA(NFA(ASSIGN))

COM_OP_dfa=DFA(NFA(COM_OP))